global:
    scrape_interval: 10s
    evaluation_interval: 10s

scrape_configs:
    # prometheus self-monitoring
    - job_name: 'prometheus'
      static_configs:
          - targets: ['localhost:9090']
    # node-exporter self monitoring
    # - job_name: 'node-exporter'
    #   static_configs:
    #       - targets: ['localhost:9100']
    - job_name: 'node-exporter'
      static_configs:
          - targets: ['xepsa-node-exporter:9100']
