global:
    scrape_interval: 10s
    evaluation_interval: 10s

scrape_configs:
    # Prometheus self-monitoring
    - job_name: 'prometheus'
      static_configs:
          - targets: ['localhost:9090']
    # node-exporter self monitoring
    - job_name: 'node-exporter'
      static_configs:
          - targets: ['localhost:9100']
